language: node_js
node_js:
  - 13
  - 12
  - 10
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
  - npm run build
jobs:
  include:
    - stage: publish coverage report
      node_js: "12"
      script:
        - npm run test
        - npm run coverage
